CREATE TABLE VENDEDOR (
    FK_USUARIO_id INTEGER PRIMARY KEY
);

CREATE TABLE IMOVEL_ENDERECO (
    id INTEGER PRIMARY KEY,
    preco FLOAT,
    categoria VARCHAR,
    tipo_pag VARCHAR,
    qtd_quartos INTEGER,
    add_infos VARCHAR,
    FK_VENDEDOR_FK_USUARIO_id INTEGER,
    cep VARCHAR,
    logradouro VARCHAR,
    bairro VARCHAR,
    cidade VARCHAR,
    estado VARCHAR
);

CREATE TABLE COMPLEMENTO (
    id INTEGER PRIMARY KEY,
    descricao VARCHAR,
    FK_ENDERECO_id INTEGER
);

CREATE TABLE USUARIO (
    id INTEGER PRIMARY KEY,
    cpf VARCHAR,
    tel VARCHAR,
    email VARCHAR,
    login VARCHAR,
    senha VARCHAR
);

CREATE TABLE CLIENTE (
    FK_USUARIO_id INTEGER PRIMARY KEY
);

CREATE TABLE Compra (
    fk_CLIENTE_FK_USUARIO_id INTEGER,
    fk_IMOVEL_ENDERECO_id INTEGER
);
 
ALTER TABLE
  VENDEDOR
ADD
  CONSTRAINT FK_VENDEDOR_2 FOREIGN KEY (FK_USUARIO_id) REFERENCES USUARIO (id) ON DELETE CASCADE;


 
ALTER TABLE
  IMOVEL_ENDERECO
ADD
  CONSTRAINT FK_IMOVEL_ENDERECO_2 FOREIGN KEY (FK_VENDEDOR_FK_USUARIO_id) REFERENCES VENDEDOR (FK_USUARIO_id) ON DELETE CASCADE;

 
ALTER TABLE COMPLEMENTO ADD CONSTRAINT FK_COMPLEMENTO_2
    FOREIGN KEY (FK_ENDERECO_id)
    REFERENCES ??? (???);
 
ALTER TABLE
  CLIENTE
ADD
  CONSTRAINT FK_CLIENTE_2 FOREIGN KEY (FK_USUARIO_id) REFERENCES USUARIO (id) ON DELETE CASCADE;


 
ALTER TABLE
  Compra
ADD
  CONSTRAINT FK_Compra_1 FOREIGN KEY (fk_CLIENTE_FK_USUARIO_id) REFERENCES CLIENTE (FK_USUARIO_id) ON DELETE
SET
  NULL;


ALTER TABLE
  Compra
ADD
  CONSTRAINT FK_Compra_2 FOREIGN KEY (fk_IMOVEL_ENDERECO_id) REFERENCES IMOVEL_ENDERECO (id) ON DELETE
SET
  NULL;
